---
title: "Plotly Example"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---


My name is Alicia and I make withside _with interactive graphics_ !!!


```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


# Let's make some graphs


```{r message = FALSE}
#Select a reasonably sized dataset
set.seed(1)

data(nyc_airbnb)
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>%
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    !is.na(rating), 
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500)  %>% 
  sample_n(5000)
```


# Let's make a scatter plot!

```{r message = FALSE}
nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, '\nRating: ', rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)

```


# Bar charts!

In plotly, to get the bar to go up to the number, we need to create a dataset that has the y values that the bar go up to.
```{r message=FALSE}
#Bar chart with observations per neighborhood
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, type= "bar")

```


